### ISSUE TITLE
add smbchk as test

### ISSUE THREAD

**Issue by gidden** [cyclus/ciclus#54]
to my knowlege, this is not yet done

**Comment by gidden** [comment]
@scopatz can confirm

**Comment by scopatz** [comment]
I think that this is done.  But should probably double check.

**Comment by gidden** [comment]
I just grepped through master and it didn't come back:
```
22:19 blackbeard-air:~/work/cyclus/ciclus [master|✔]$ git pull up master
X11 forwarding request failed on channel 0
From github.com:cyclus/ciclus
 * branch            master     -> FETCH_HEAD
Already up-to-date.
22:19 blackbeard-air:~/work/cyclus/ciclus [master|✔]$ ack-grep smbchk.py
22:19 blackbeard-air:~/work/cyclus/ciclus [master|✔]$ ack-grep smbchk
22:19 blackbeard-air:~/work/cyclus/ciclus [master|✔]$
```

On Thu, Jan 15, 2015 at 10:15 PM, Anthony Scopatz <notifications@github.com>
wrote:

> I think that this is done. But should probably double check.
>
> On Thu, Jan 15, 2015, 10:14 PM Matthew Gidden <notifications@github.com>
> wrote:
>
> > @scopatz <https://github.com/scopatz> can confirm
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/ciclus/issues/54#issuecomment-70206185>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/issues/54#issuecomment-70206241>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
It wouldn't come back on this repo because it has been added as a test to cyclus/cyclus.  Rather you can tell from here that the smbchk test is being skipped: http://submit-1.batlab.org/nmi-runs/cyclusci/2015/01/cyclusci_submit-1.batlab.org_1420901551_1385/userdir/nmi:x86_64_Ubuntu12/remote_task.err

**Comment by gidden** [comment]
Ok, let me close this and bring it up on the cyclus repo

On Thu, Jan 15, 2015 at 10:43 PM, Anthony Scopatz <notifications@github.com>
wrote:

> It wouldn't come back on this repo because it has been added as a test to
> cyclus/cyclus. Rather you can tell from here that the smbchk test is being
> skipped:
> http://submit-1.batlab.org/nmi-runs/cyclusci/2015/01/cyclusci_submit-1.batlab.org_1420901551_1385/userdir/nmi:x86_64_Ubuntu12/remote_task.err
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/ciclus/issues/54#issuecomment-70207755>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192
